app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.home, name="home"),
    path("timeline/", views.timeline, name="timeline"),
    path("timeline/add_post/", views.add_post, name="add_post"),
    path("reminder/", views.reminder, name="reminder"),
    path("toggle_like/<int:post_id>/", views.toggle_like, name="toggle_like"),
    path("timeline/comment/<int:post_id>/", views.comment, name="comment"),
    path("chat/", views.chat, name="chat"),
    path("chat/search_users/", views.search_users, name="search_users"),
    path("chat/create_table/", views.create_chat, name="create.chat"),
    path("chat/<int:send_chat_id>/", views.message, name="message"),
    path("tag_list/", views.tag_list, name="tag_list"),
    path("profile/profile_change/", views.profile_change, name="profile_change"),
    path("profile/<str:user_id>/", views.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbyLinkApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("top.urls")),
    path("user/", include("user.urls")),
    path("hobbyLink/", include("app.urls"))
]

app/models.py
from django.db import models
from user.models import User
from django.utils import timezone

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

def get_current_time():
    return timezone.now()

class Post_data(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    post_time = models.DateTimeField(auto_now_add=True)
    post_text = models.TextField()
    # post_tag = models.TextField()
    # def __str__(self):
        # return self.user_id



class Comment(models.Model):
    post_id = models.ForeignKey(Post_data, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    created_at = models.DateTimeField(default=get_current_time)
    
    def __str__(self):
        return self.comment_text

class Like(models.Model):
    post_id = models.ForeignKey(Post_data, on_delete=models.CASCADE)
    like_num = models.IntegerField(default=0)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE ) 
    
    def __str__(self):
        return str(self.like_num)

class Favorite(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    favorite_post_id = models.ForeignKey(Post_data, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.favorite_post_id

class Tag(models.Model):
    tag = models.CharField(max_length=20, unique=True)
    
    def __str__(self):
        return self.tag

class Image(models.Model):
    post_id = models.ForeignKey(Post_data, on_delete=models.CASCADE, related_name='images')
    filename = models.CharField(max_length=255)
    
    def __str__(self):
        return self.filename


class Chat(models.Model):
    name = models.CharField(max_length=50)

class ChatMember(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Message(models.Model):
    chat_id = models.ForeignKey(Chat, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.CharField(max_length=100, null=True)

class Post_tag(models.Model):
    post_id = models.ForeignKey(Post_data, on_delete=models.CASCADE)
    tag_id = models.ForeignKey(Tag, on_delete=models.CASCADE)

# @receiver(post_save, sender=Chat)
# def add_members_to_chat(sender, instance, created, **kwargs):
#     if created and not instance.is_group:
#         ChatMember.objects.create(chat=instance, user=instance.user1)
#         ChatMember.objects.create(chat=instance, user=instance.user2)

app/templates/add_post.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/add_post.css' %}">
{% endblock %}

{% block title %}
投稿する
{% endblock %}

{% block content %}
<div class="content">
    <form method="post" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="post_header">
            <h3 class="user_name">{{ user_name }}</h3>
            <h4 class="user_id">@{{ user_id }}</h4>
        </div>
        <div class="post_body">
            <textarea name="post_text" placeholder="投稿内容を入力してください（必須）"></textarea>
        </div>
        <div class="post_tag">
            <input type="text" placeholder="タグを入力してください（例）#サイクリング #サイクリング好きとつながりたい" id="tag_input" name="tag">
            <div id="suggestions" class="suggestions"></div>
        <div class="img_file">
            <input type="file" name="post_images">
        </div>
        <div class="add_img">
            <button type="button" id="add_img">+</button>
        </div>
        <button type="submit">投稿する</button>
    </form>
</div>


{% endblock %}

{% block javascript %}
<script src="{% static 'js/add_post.js' %}"></script>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <main>
        <div class="nav">
            <h1>hobbyLink</h1>
            <nav>
                <ul>
                    <li><a href="/hobbyLink/">Home</a></li>
                    <li><a href="/hobbyLink/profile/{{ request.session.user_id }}/">プロフィール</a></li>
                    <li><a href="/hobbyLink/timeline/">タイムライン</a></li>
                    <li><a href="/hobbyLink/chat/">チャット</a></li>
                </ul>
            </nav>
        </div>
        {% block content %}
        {% endblock %}
        {% block javascript %}
        {% endblock %}
    </main>
</body>

</html>

app/templates/chat.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/chat.css' %}">
{% endblock %}

{% block title %}
チャット
{% endblock %}

{% block content %}
<div class="content">
    <section class="friends">
        <div class="friends_header">
            <h2 id="new_chat">新しいチャットを始める</h2>
        </div>
        <div class="friends_body">
            {% for chat in chat_data %}
                <h2 class="friend_name" id="chat-{{ chat.id }}">{{ chat.name }}</h2>
            {% endfor %}
        </div>
    </section>
    {% for chat in chat_data %}
        <section  id="chat_body-{{ chat.id }}" class="chat">
            <div class="chat_header">
                <h2>グループ名</h2>
            </div>
            
                <div class="chat_body">
                {% for message in chat.message_set.all %}
                    <div class="{% if message.sender.user_id|to_str == login_user %}my{% endif %}">
                        <h3>{{ message.sender.user_name }}</h3>
                        {% if message.text != "" %}
                            {% if message.sender.user_id|to_str == login_user %}
                                <p>{{ message.timestamp|date:"H:i" }}<span class="text">{{ message.text }}</span></p>
                            {% else %}
                                <p><span class="text">{{ message.text }}</span>{{ message.timestamp|date:"H:i" }}</p>
                            {% endif %}
                        {% endif %}
                        {% if message.image %}
                        <img src="{% static 'images/chat_img/' %}{{ message.image }}" alt="">
                        {% endif %}
                    </div>
                {% endfor %}
                </div>
            
            <div class="chat_footer-{{ chat.id }}">
                <form action="{{ chat.id }}/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" id="send_image" name="image">
                    <input type="text" id="send_text" name="text">
                    <button type="submit" id="send">送信</button>
                </form>
            </div>
        </section>
    {% endfor %}
    <section class="friend_search">
        <h1>チャットを始める</h1>
        <input type="text" id="user_search" autocomplete="new-password">
        <div id="suggestions" class="suggestions_list"></div>
    </section>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/chat.js' %}"></script>
<script src="{% static 'js/user_search.js' %}"></script>
<script src="{% static 'js/create_chat.js' %}"></script>
{% endblock %}

app/templates/comment.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/comment.css' %}">
{% endblock %}

{% block title %}

{% endblock %}

{% block content %}
<div class="content">
    <section class="post_section">
        
        
        <div class="post_comment">
            <div class="post" id="post-{{ post.id }}" >
                <div class="post_header">
                    <h3 class="user_name">{{ post.user_id.user_name }}<span class="user_id">@{{ post.user_id }}</span></h3>
                    <h4 class="time">{{ post.post_time }}</h4>
                </div>
                <div class="post_body">
                    <p>{{ post.post_text }}</p>
                </div>
                <div class="post_tag"></div>
                <div class="post_footer">
                    <form id="like-form-{{ post.id }}" action="" method="POST">
                        {% csrf_token %}

                        <h3><i class="fa-solid fa-comment"></i></h3>
                        <h3>
                            <i class="fa-solid fa-heart" id="like-icon-{{ post.id }}" onclick="toggleLike({{ post.id }})"></i>
                            <span id="like-count-{{ post.id }}">{{ like }}</span>
                        </h3>
                        <h3 id="star"><i class="fa-solid fa-star"></i></h3>
                    </form>
                </div>
            </div>
            
            <div class="comment_data">
                {% for comment in comments %}
                    <div class="comment">
                        <div class="comment_header">
                            <h3 class="user_name">{{ comment.user_id.user_name }}<span class="user_id">@{{ comment.user_id }}</span></h3>
                            <h4 class="time">{{ comment.created_at }}</h4>
                        </div>
                        <div class="comment_body">
                            <p>{{ comment.comment_text }}</p>
                        </div>
                        <div class="comment_footer">
        
                        </div>
                    </div>
                {% endfor %}
            </div>
            
        </div>
        <form action="/hobbyLink/timeline/comment/{{ post.id }}/" class="comment_form" method="post">
            {% csrf_token %}
            <input type="text" name="comment">
            <button type="submit">送信する</button>
        </form>
    </section>
    <section class="img_section">
        
    </section>
</div>
{% endblock %}


{% block javascript %}
<script src="{% static 'js/like.js' %}"></script>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="content">
    <div class="left">
        <section class="trend_post">
            <h1>話題の投稿</h1>
            {% for post in post_data %}
            <div class="post">
                <div class="user_name">{{ post.user_id.user_name }}</div>
                <div class="post_content">{{ post.post_text }}</div>
                <div class="time">{{ post.post_time }}</div>
            </div>
            
            {% endfor %}
        </section>
    </div>
    <div class="right">
        <section class="trend_tag">
            <h1>注目のタグ</h1>
            {% for tag in favorite_tag %}
                
            <div class="tag">
                <div class="name">{{ tag.tag_id__tag }}</div>
                <div class="count">{{ tag.tag_count }}件の投稿</div>
            </div>
            {% endfor %}
        </section>
        <!-- <section class="reminder">
            <h1>通知</h1>
            <div class="item">
                <div class="title">リマインダー1</div>
                <div class="description">ここにリマインダーの内容が表示されます...</div>
                <div class="time">1時間前</div>
            </div>
            <div class="item">
                <div class="title">リマインダー2</div>
                <div class="description">ここにリマインダーの内容が表示されます...</div>
                <div class="time">2時間前</div>
            </div>
        </section> -->
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block title %}
プロフィール
{% endblock %}

{% block content %}
<div class="content">
    <section class="header">
        <div class="img">
            {% if user.user_icon != "" %}
                <img src="{% static 'images/profile_icon/' %}{{ user.user_icon }}" alt="">
            {% else %}
                <img src="{% static 'images/profile_icon/nomal.png' %}" alt="" style="object-fit: contain;">
            {% endif %}
        </div>
        <div class="user">
            {% if my_user_id %}
            <a href="/hobbyLink/profile/profile_change/">編集</a>
            {% endif %}
            <h1 {% if not my_user_id %}style="margin-top: 5vh;"{% endif %}>{{ user.user_name }}<span>@{{ user.user_id }}</span></h1>
            <p>{{ user.profile_text }}</p>
        </div>
    </section>
    <section class="user_post">
        <div class="post_list">
            {% for post in posts_with_related_data %}
            <div class="post_comment">
                <div class="post" id="post-{{ post.id }}" onclick="getPostId(this.id)">
                    <div class="post_header">
                        <h3 class="user_name">{{ post.user_id.user_name }}<span class="user_id">@{{ post.user_id }}</span></h3>
                        <h4 class="time">{{ post.post_time }}</h4>
                    </div>
                    <div class="post_body">
                        <p>{{ post.post_text }}</p>
                    </div>
                    <div class="post_tag">
                        {% for tag in post.post_tag_set.all %}
                            {{ tag.tag_id.tag }}
                        {% endfor %}
                    </div>
                    <div class="post_footer">
                        <form id="like-form-{{ post.id }}" action="{% url 'toggle_like' post.id %}" method="POST">
                            {% csrf_token %}
    
                            <h3 onclick="comment(event, {{ post.id }})">
                                <i class="fa-solid fa-comment"></i>{{ post.comment_set.count }}
                            </h3>
                            <h3>
                                <i class="fa-solid fa-heart" id="like-icon-{{ post.id }}" onclick="toggleLike({{ post.id }})"></i>
                                <span id="like-count-{{ post.id }}">{{ post.like_set.count }}</span>
                            </h3>
                            <h3 id="star"><i class="fa-solid fa-star"></i></h3>
                        </form>
                    </div>
                </div>
                
            </div>
            {% endfor %}
        </div>
        <div class="img_list">
            {% for post in posts_with_related_data %}
            {% for image in post.images.all %}
                {% if not image == "" %}
                    {% if forloop.first %}
                    <div id="post_img-{{ post.id }}" class="post_img" style="display: none;">
                    
                    {% endif %}
                    <div>
                        <img src="{% static 'images/post_img/' %}{{ image.filename }}" alt="">
                    </div>
                    {% if forloop.last %}
                    </div>
                    {% endif %}
                {% else %}
                    <h2>画像は投稿されていません</h2>
                {% endif %}
            {% endfor %}
        {% endfor %}
        </div>
    </section>
</div>
{% endblock %}


{% block javascript %}
<script src="{% static 'js/fixed.js' %}"></script>
<script src="{% static 'js/timeline.js' %}"></script>
<script src="{% static 'js/like.js' %}"></script>

{% endblock %}

app/templates/profile_change.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/profile_change.css' %}">
{% endblock %}

{% block title %}

{% endblock %}

{% block content %}
<div class="content">
    <form class="header" action="" method="post"  enctype="multipart/form-data">
        {% csrf_token %}
        <div class="img">
            <input type="file" id="file" name="user_icon" class="user_icon" accept="image/*" onchange="previewImage(event)">
            <label for="file" id="file-label">
                {% if change_user.user_icon == "" %}
                    <i class="fa-solid fa-plus"></i>
                {% else %}
                    <img src="{% static 'images/profile_icon' %}/{{ change_user.user_icon }}" alt="">
                {% endif %}
            </label>
        </div>
        <div class="user">
            <input type="text" name="user_name" class="user_name" placeholder="ユーザー名を入力して下さい" value="{{ change_user.user_name }}">
            <textarea name="profile_text" id="" placeholder="プロフィールを入力してください"></textarea>
            <button type="submit">完了</button>
        </div>
    </form>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/profile_change.js' %}"></script>
{% endblock %}

app/templates/reminder.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/reminder.css' %}">
{% endblock %}

{% block title %}
リマインダー
{% endblock %}

{% block content %}
<div class="content">
    <div class="reminder">
        <section class="timeline_reminder">
            <div class="reminder_name">
                <h2>タイムライン</h2>
            </div>
            <div class="reminder_text_area">
                <div class="reminder_text">
                    <h4>10:05</h4><h3>あなたの投稿にいいねがつきました</h3>
                </div>
                
            </div>
        </section>
        <section class="chat_reminder">
            <div class="reminder_name">
                <h2>チャット</h2>
            </div>
            <div class="reminder_text_area">
                <div class="reminder_text">
                    <h4>10:05</h4><h3>虎さんがグループに参加しました</h3>
                </div>
                <div class="reminder_text">
                    <h4>10:05</h4><h3>虎さんがグループに参加しました</h3>
                </div>
                <div class="reminder_text">
                    <h4>10:05</h4><h3>虎さんがグループに参加しました</h3>
                </div>
                <div class="reminder_text">
                    <h4>10:05</h4><h3>虎さんがグループに参加しました</h3>
                </div>
            </div>
        </section>
    </div>
    

</div>
{% endblock %}

{% block javascript %}

{% endblock %}


app/templates/timeline.html
<!-- 投稿された文章を左に、画像がある場合は右に表示する感じはどうか -->
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/timeline.css' %}">
{% endblock %}

{% block title %}
タイムライン
{% endblock %}

{% block content %}
<div class="content">
    <section class="post_section">
        <form action="" class="post_search">
            <input type="text" name="post_search">
            <button type="submit">検索</button>
        </form>
        {% for post in posts_with_related_data %}
        <div class="post_comment">
            <div class="post" id="post-{{ post.id }}" onclick="getPostId(this.id)">
                <div class="post_header">
                    <h3 class="user_name"><a href="/hobbyLink/profile/{{ post.user_id }}/">{{ post.user_id.user_name }}<span class="user_id">@{{ post.user_id }}</span></a></h3>
                    <h4 class="time">{{ post.post_time }}</h4>
                </div>
                <div class="post_body">
                    <p>{{ post.post_text }}</p>
                </div>
                <div class="post_tag">
                    {% for tag in post.post_tag_set.all %}
                        {{ tag.tag_id.tag }}
                    {% endfor %}
                </div>
                <div class="post_footer">
                    <form id="like-form-{{ post.id }}" action="{% url 'toggle_like' post.id %}" method="POST">
                        {% csrf_token %}
                        <h3 onclick="comment(event, {{ post.id }})">
                            <i class="fa-solid fa-comment"></i>{{ post.comment_set.count }}
                        </h3>
                        <h3>
                            <i class="fa-solid fa-heart" id="like-icon-{{ post.id }}" onclick="toggleLike({{ post.id }})"></i>
                            <span id="like-count-{{ post.id }}">{{ post.like_set.count }}</span>
                        </h3>
                        <h3 id="star"><i class="fa-solid fa-star"></i></h3>
                    </form>
                </div>
            </div>
            
        </div>
        
        {% endfor %}
        <div class="post_add">
            <a href="add_post/">+</a>
        </div>
    </section>
    <section class="img_section">
        {% for post in posts_with_related_data %}
            {% for image in post.images.all %}
                {% if not image == "" %}
                    {% if forloop.first %}
                    <div id="post_img-{{ post.id }}" class="post_img" style="display: none;">
                    
                    {% endif %}
                    <div>
                        <img src="{% static 'images/post_img/' %}{{ image.filename }}" alt="">
                    </div>
                    {% if forloop.last %}
                    </div>
                    {% endif %}
                {% else %}
                    <h2>画像は投稿されていません</h2>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </section>
</div>
{% endblock %}


{% block javascript %}
<script src="{% static 'js/timeline.js' %}"></script>
<script src="{% static 'js/like.js' %}"></script>

{% endblock %}